//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampsScientifiques_Console
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jeune
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jeune()
        {
            this.HistoriqueCamps = new HashSet<Camp>();
        }
    
        public int oidJeune { get; set; }
        public string Nom { get; set; }
        public int NiveauComplete { get; set; }
        public int AgeCourant { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Camp> HistoriqueCamps { get; set; }
    }
}
